### ISSUE TITLE
1.11 Problem

### ISSUE THREAD

**Issue by SimonVanacco** [keybordpiano459/Newspaper#1]
I know that this plugin is very old, but it's still very convenient.
Perhaps you could have the possibility to fix this error in Bukkit 1.11:

`[00:19:35] [Craft Scheduler Thread - 1297/WARN]: [Newspaper] Plugin Newspaper v1.3.1 generated an exception while executing task 10
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at me.KeybordPiano459.Newspaper.BukkitMetrics.postPlugin(BukkitMetrics.java:188) ~[?:?]
	at me.KeybordPiano459.Newspaper.BukkitMetrics.access$400(BukkitMetrics.java:27) ~[?:?]
	at me.KeybordPiano459.Newspaper.BukkitMetrics$1.run(BukkitMetrics.java:121) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_11.jar:git-Spigot-f950f8e-655d840]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot-v1_11.jar:git-Spigot-f950f8e-655d840]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]`

Thank you.

**Comment by SimonVanacco** [comment]
Apparently it comes from the metrics, going to fork your project and disable all metrics. We'll see soon.
Would you be interested in a pull request?
